from __future__ import annotations

import base64
import zlib
from pathlib import Path, PurePosixPath


RESOURCE_DIRS = (
    'Locale',
    'Themes',
)

OUTPUT_PATH = Path('src/gpmi_launcher/core/resources_bundle.py')

SKIP_FILENAMES = {
    'active_locale.cfg',
}

SKIP_SUFFIXES = {
    '.bak',
    '.log',
    '.tmp',
}


def normalize_resource_path(path: Path) -> str:
    return PurePosixPath(*path.parts).as_posix()


def should_include(path: Path) -> bool:
    if path.name in SKIP_FILENAMES:
        return False
    if path.suffix.lower() in SKIP_SUFFIXES:
        return False
    if any(part.startswith('.') for part in path.parts):
        return False
    if any(part == '__pycache__' for part in path.parts):
        return False
    return path.is_file()


def encode_file(path: Path) -> str:
    data = path.read_bytes()
    compressed = zlib.compress(data, level=9)
    return base64.b85encode(compressed).decode('ascii')


def main() -> int:
    repo_root = Path.cwd()
    files: dict[str, str] = {}
    dirs: set[str] = set()

    for resource_dir_name in RESOURCE_DIRS:
        resource_dir = repo_root / resource_dir_name
        if not resource_dir.is_dir():
            print(f'[WARN] Resource directory not found: {resource_dir_name}')
            continue

        dirs.add(resource_dir_name)
        for path in sorted(resource_dir.rglob('*')):
            rel_path = path.relative_to(repo_root)
            rel_text = normalize_resource_path(rel_path)

            if path.is_dir():
                dirs.add(rel_text)
                continue

            if not should_include(rel_path):
                continue

            files[rel_text] = encode_file(path)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open('w', encoding='utf-8', newline='\n') as f:
        f.write('# This file is generated by tools/build_resources_bundle.py.\n')
        f.write('# Do not edit manually.\n\n')
        f.write('FILES = {\n')
        for rel_path, payload in sorted(files.items()):
            f.write(f'    {rel_path!r}: {payload!r},\n')
        f.write('}\n\n')
        f.write('DIRS = [\n')
        for rel_path in sorted(dirs):
            f.write(f'    {rel_path!r},\n')
        f.write(']\n')

    print(f'[OK] Wrote {OUTPUT_PATH} with {len(files)} files and {len(dirs)} directories.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
